In [2]:
#read in pkl
import pickle
import numpy as np

with open('rtr_reviews_uncleaned.pkl', 'rb') as f:
    data = pickle.load(f)
data

#open category dict json
import json
with open('category_dict.json') as f:
    category_dict = json.load(f)
category_dict

{'fit': {'fit': 0, 'large': 1, 'small': 2},
 'rating': {'2': 0, '4': 1, '6': 2, '8': 3, '10': 4},
 'rented for': {'date': 0,
  'everyday': 1,
  'formal affair': 2,
  'other': 3,
  'party': 4,
  'vacation': 5,
  'wedding': 6,
  'work': 7},
 'body type': {'apple': 0,
  'athletic': 1,
  'full bust': 2,
  'hourglass': 3,
  'pear': 4,
  'petite': 5,
  'straight & narrow': 6},
 'category': {'dress': 0,
  'jumpsuit': 1,
  'other': 2,
  'outerwear': 3,
  'pants': 4,
  'skirt': 5,
  'top': 6},
 'subcategory': {'blazer': 0,
  'blouse': 1,
  'coat': 2,
  'dress': 3,
  'gown': 4,
  'jacket': 5,
  'jumpsuit': 6,
  'leggings': 7,
  'maxi_dress': 8,
  'mini_dress': 9,
  'other': 10,
  'other_dress': 11,
  'other_outer': 12,
  'other_pants': 13,
  'pant': 14,
  'pants': 15,
  'romper': 16,
  'sheath_dress': 17,
  'shift_dress': 18,
  'shirt': 19,
  'shorts': 20,
  'skirt': 21,
  'suit': 22,
  'sweater': 23,
  'sweatshirt': 24,
  'tank': 25,
  'top': 26},
 'size': {'0': 0,
  '1': 1,
  '2': 2,
  '3': 3,
  '4': 4,
  '5': 5,
  '6': 6,
  '7': 7,
  '8': 8,
  '9': 9,
  '10': 10,
  '11': 11,
  '12': 12,
  '13': 13,
  '14': 14,
  '15': 15,
  '16': 16,
  '17': 17,
  '18': 18,
  '19': 19,
  '20': 20,
  '21': 21,
  '22': 22,
  '23': 23,
  '24': 24,
  '25': 25,
  '26': 26,
  '27': 27,
  '28': 28,
  '29': 29,
  '30': 30,
  '32': 31,
  '33': 32,
  '34': 33,
  '35': 34,
  '36': 35,
  '37': 36,
  '38': 37,
  '39': 38,
  '40': 39,
  '41': 40,
  '42': 41,
  '43': 42,
  '44': 43,
  '45': 44,
  '46': 45,
  '48': 46,
  '49': 47,
  '50': 48,
  '51': 49,
  '52': 50,
  '54': 51,
  '55': 52,
  '56': 53,
  '57': 54,
  '58': 55},
 'cup_size': {'a': 0,
  'aa': 1,
  'b': 2,
  'c': 3,
  'd': 4,
  'd+': 5,
  'dd': 6,
  'ddd': 7,
  'f': 8,
  'g': 9,
  'h': 10,
  'i': 11,
  'j': 12},
 'band_size': {'28': 0,
  '30': 1,
  '32': 2,
  '34': 3,
  '36': 4,
  '38': 5,
  '40': 6,
  '42': 7,
  '44': 8,
  '46': 9,
  '48': 10}}

In [4]:
data

,fit,user_id,item_id,weight,rating,rented for,review_text,body type,review_summary,height,size,age,review_date,summary,band_size,cup_size,category,subcategory
0,fit,420272,2260466,137.0,10.0,vacation,An adorable romper! Belt and zipper were a lit...,hourglass,So many compliments!,68,14,28,2016-04-20,"137lbs-5' 8""-34d-hourglass-28.0",34,d,jumpsuit,romper
1,fit,273551,153475,132.0,10.0,other,I rented this dress for a photo shoot. The the...,straight & narrow,I felt so glamourous!!!,66,12,36,2013-06-18,"132lbs-5' 6""-34b-straight & narrow-36.0",34,b,dress,gown
2,fit,360448,1063761,NaN,10.0,party,This hugged in all the right places! It was a ...,NaN,It was a great time to celebrate the (almost) ...,64,4,116,2015-12-14,"nan-5' 4""-nan-nan-116.0",NaN,NaN,dress,sheath_dress
3,fit,909926,126335,135.0,8.0,formal affair,I rented this for my company's black tie award...,pear,Dress arrived on time and in perfect condition.,65,8,34,2014-02-12,"135lbs-5' 5""-34c-pear-34.0",34,c,dress,dress
4,fit,151944,616682,145.0,10.0,wedding,I have always been petite in my upper body and...,athletic,Was in love with this dress !!!,69,12,27,2016-09-26,"145lbs-5' 9""-34b-athletic-27.0",34,b,dress,gown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192350,fit,66386,2252812,140.0,10.0,work,Fit like a glove!,hourglass,LOVE IT!!! First Item Im thinking of buying!,69,8,42,2016-05-18,"140lbs-5' 9""-34dd-hourglass-42.0",34,dd,jumpsuit,jumpsuit
192351,fit,118398,682043,100.0,10.0,work,The pattern contrast on this dress is really s...,petite,LOVE it!,61,4,29,2016-09-30,"100lbs-5' 1""-32c-petite-29.0",32,c,dress,dress
192352,fit,47002,683251,135.0,6.0,everyday,"Like the other DVF wraps, the fit on this is f...",straight & narrow,"Loud patterning, flattering fit",68,8,31,2016-03-04,"135lbs-5' 8""-36a-straight & narrow-31.0",36,a,dress,dress
192353,fit,961120,126335,165.0,10.0,wedding,This dress was PERFECTION. it looked incredib...,pear,loved this dress it was comfortable and photog...,66,16,31,2015-11-25,"165lbs-5' 6""-36c-pear-31.0",36,c,dress,dress
192354,fit,123612,127865,155.0,10.0,wedding,This dress was wonderful! I had originally pla...,athletic,I wore this to a beautiful black tie optional ...,66,16,30,2017-08-29,"155lbs-5' 6""-36b-athletic-30.0",36,b,dress,gown

In [8]:
#print review_text for the first revire
data[0]['review_text']

KeyError: 0